---
title: "EDS 212 Day 2"
author: "Wylie Hampson"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

## First order univaritive derivatives:

```{r}
eq_1 <- expression(x ^ 2)

df_dx <- D(expr = eq_1, name = 'x')

x <- 3

eval(expr = df_dx)
```
```{r}
eq_2 <- expression(2 * ((3 * a + 2) ^ 4) - 5)

dP_da <- D(expr = eq_2, name = 'a')

a <- 1.2

eval(expr = dP_da)
```
```{r}
eq_3 <- expression(-4 * t / ((t ^ 2 + 1) ^ 3))

dg_dt <- D(expr = eq_3, name = 't')

t <- 0

eval(expr = dg_dt)
```

## Find the second derivative with respect to z.

$G(z) = 4.6-1.9z^3$

```{r}
eq_4 <- expression(4.6 - 1.9 * (z ^ 3))

dG_dz <- D(expr = eq_4, name = 'z')

dG_dz

d2G_d2z <- D(expr = dG_dz, name = 'z')

d2G_d2z

```

### Partial derivatives

Find all partial derivatives for $f(x,y,z)=2x^2y-3x+1+4z^4x$

```{r}
eq_5 <- expression((2 * (x ^ 2) * y) - (3 * x) + 1 + (4 * (z ^ 4) * x))

df_dx <- D(expr = eq_5, name = 'x')

df_dx

df_dy <- D(expr = eq_5, name = 'y')

df_dy

df_dz <- D(expr = eq_5, name = 'z')

df_dz

```

### Make some plots!

```{r}
eq <- function(x) {
  
  2.4 * exp(-0.05 * x) * sin(x)
  
}

ggplot(data.frame(x = c(-0.5, 0.5)), aes(x = x)) +
  stat_function(fun = eq)

```
```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  labs(x = "Bill length (mm)",
       y = "Bill depth (mm)",
       title = "Palmer Penguin Bill Measurements",
       caption = "Data collected by KB Gormer et al. at Palmer Station") +
  theme_light()
```
```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species)) +
  labs(x = "Flipper length (mm)",
       y = "Species",
       title = "Penguin Flipper Length by Species",
       caption = "Data collected by KB Gormer et al. at Palmer Station") +
  theme_light()
```

